### ISSUE TITLE
error running

### ISSUE THREAD

**Issue by isso11** [AndersonRayner/ulgReader#1]
Hi @AndersonRayner 

I cannot get the rep to work on Matlab. 
 I got this error:

`ulgReader
Reading v1 .ulg file - Header OK!
	Processing File
Don't recognise type <<Q>>
Don't recognise type <<l>>
Don't recognise type << >>
Don't recognise type <<1>>
Unrecognized function or variable 'value'.

Error in ulgReader>param_message (line 539)
fds.param.(param_name) = value;

Error in ulgReader (line 87)
            fds = param_message(fds,msg_size);`

**Comment by AndersonRayner** [comment]
If you send me the .`ulg` file you were having trouble with, I can take a look and see what might be causing the issue.  Unfortunately, those error messages aren't giving up any clues so I would need to do some debugging.  Does the log load when you pass it through [Flight Review](https://logs.px4.io/)?

**Comment by isso11** [comment]
@AndersonRayner ,
Thank you for replying. The ulog file perfectly works on Flight Review.
I think the error is mainly in the line calling ulog2csv.
(The ulog2scv also works perfect in system cmd)
I tried to trace the code line by line, but got lost in the variables and directories.

**Comment by isso11** [comment]
Thank you for replying. 
The ulog works perfectly in Flight Review.
I might not be able to send you the ulog file atm. But I'm sure it is working.

**Comment by AndersonRayner** [comment]
Without the original ulog file there's really not much I can do to debug it correctly.  My suggestion for now would be to disable the [parameter import functionality](https://github.com/AndersonRayner/ulgReader/blob/a45e12c30f505f1778808722ce9c40d186c4942e/ulgReader.m#L87) as this is what's causing the problem (just comment the line out) and see if the system works from there.  We could put error handling logic in here, however that can hide underlying problems with the code hence I'd prefer not to do for now (but am open to the idea).

If you can provide a quick log (I understand people not wanting to share locations, etc.) of just the vehicle resting inside (follow the instructions [here](https://docs.px4.io/v1.12/en/dev_log/logging.html) I can take a look.  It will have the parameters in it which is what I'm mainly interested in.  Does the import fail for just one or all of your logs?

**Comment by AndersonRayner** [comment]
Hi @isso11  - did the script run with the change I suggested?

**Comment by isso11** [comment]
Yes. It worked! 
Thank you!

**Comment by AndersonRayner** [comment]
Cool.  I'm going to close out this issue then, but feel free to open it up again if you see the issue again.  If you see it with any new logs, it'd be great to get a log from you, otherwise I'll flash one of my UAVs over to PX4 as the PX4 log system might have introduced something new I didn't code in originally.  Cheers!
